# Generated by Django 4.0.1 on 2023-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeolder.png', null=True, upload_to='images'),
        ),
    ]
